
name = "vibrate-data-system"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[env.production]
vars = { ENVIRONMENT = "production" }

[env.development]
vars = { ENVIRONMENT = "development" }


binding = "DB"
database_name = "vibrate-data"
database_id = "6dacb313-22e3-4b58-8df9-d50aa6e5b038"
migrations_dir = "database/migrations"
